export const ADD_DATA_TO_ORDER = "ADD_DATA_TO_ORDER";
export const ADD_DATA_TO_ORDER_BOOK = "ADD_DATA_TO_ORDER_BOOK";
export const ADD_DATA_TO_LAST_ORDER = "ADD_DATA_TO_LAST_ORDER";
export const ADD_DATA_TO_CHART = "ADD_DATA_TO_CHART";
export const UPDATE_TABS_LEFT_BODY = "UPDATE_TABS_LEFT_BODY";
export const UPDATE_TABS_RIGHT_BODY = "UPDATE_TABS_RIGHT_BODY";
